### PR TITLE
Noting standard 18F Pages site install instructions in readme

### PR DESCRIPTION
**Pull request by brittag**
To help people make changes even if they aren't already familiar with 18F Pages.

### CODE REVIEW

**Comment by afeld** [comment]
There are actually instructions here already:

https://github.com/18F/before-you-ship/blob/18f-pages/CONTRIBUTING.md

Should we move them?

**Comment by brittag** [comment]
Ah I didn't notice this there, thanks! I do like having the commands in the readme - I inevitably forget them (despite having worked on a zillion Pages mini-sites), so a quick reference is nice.

**Comment by afeld** [comment]
The same information living in multiple places is a pet peeve of mine...could we only have them in the README, or just say in the README "look in CONTRIBUTING for the setup instructions"? No strong feelings one way or the other.

**Comment by brittag** [comment]
Good point, I agree with not duplicating this info! Either way is fine with me too.

**Comment by NoahKunin** [comment]
No children were split in twain in the making of this pull request.

**Pull request merged**
