### PR TITLE
Federalist and 18F Pages don't make "websites"

### PR DESCRIPTION
**Pull request by wslack**
Would prefer to be clearer and state they build and host static web pages. I don't think the term "website" is incorrect, but its more ambiguous than I'd prefer since it makes a collection of pages sound like a standalone system.

cc @NoahKunin and @jezhumble

### CODE REVIEW

**Comment by afeld** [comment]
I'm kinda 👎  on this change...the distinction is pedantic, and while the new language isn't incorrect, it isn't how static site (👈 ) builders are generally used. If, however, this change will ease any compliance headaches, then I am **more than happy** to merge it.

**Comment by wslack** [comment]
I think my core fear is when selling Federalist, and agency might say:

> this IAA says we are getting a "website," which sounds like an individual system, which therefore needs an ATO.

I would much rather say that Federalist is a single system that publishes many static web pages (which users may experience as a unified website). But if this is pedantic and not helpful, then there's no need.

**Comment by afeld** [comment]
Anyone else want to tip this one way or the other?

**Comment by afeld** [comment]
A compromise would be to keep the text as it is, but add a footnote of "technically static site builders are just adding a collection of pages in an existing system, hence being able to stay in the same security boundary, and thus ATO".

**Comment by wslack** [comment]
@afeld I accept the compromise with open arms and a wide smile

**Comment by NoahKunin** [comment]
Infrastructure is 😐 on this. Leave it up to the Federalist team to control their marketing in this context, as either version has the same legal, policy, and regulatory meaning.

**Comment by wslack** [comment]
@NoahKunin I think the change will help other agencies with their own internal comms. This is more about helping our partners with understanding what Federalist does than a strict GSA definition.

**Comment by afeld** [comment]
@wslack Does the new footnote work for you?

**Comment by wslack** [comment]
👍 @afeld

**Pull request merged**
