### PR TITLE
Add instructions around Gemnasium

### PR DESCRIPTION
**Pull request by cmc333333**
Includes the JS workaround

### CODE REVIEW

**Comment by afeld** [comment]
Obnoxious that these hacks are needed., but thanks for adding. Any chance you've reached out to Gemnasium about the issues?

**Comment by cmc333333** [comment]
Last I had heard, @NoahKunin had. but I don't know when that was or what came of it. Their support people recently posted in one of our [PRs](https://github.com/18F/omb-eregs/pull/7#issuecomment-274494228), though, so it might be time to retry.

**Comment by gonzoyumo** [comment]
Hi there, Olivier from Gemnasium.

I just replied in the other discussion here: https://github.com/18F/omb-eregs/pull/7#issuecomment-274651340

I'll be pleased to help you to fix that.

**Comment by NoahKunin** [comment]
@gonzoyumo Closing the loop here too. Now see http://support.gemnasium.com/forums/236528-general/suggestions/17864956-support-extremely-large-github-organizations

**Pull request merged**
