### PR TITLE
clarify how changes are accepted

### PR DESCRIPTION
**Pull request by ultrasaurus**
addresses issues #21

### CODE REVIEW

**Comment by mbland** [comment]
LGTM, but we should probably let @leahbannon take a peek and perhaps have @emileighoutlaw or @awfrancisco review for style.

**Comment by ultrasaurus** [comment]
@emileighoutlaw need a little more context for "rather than --, we use —" 

do you mean for " -- a +1 by itself will typically be interpreted as your thinking its a good idea, but not having reviewed in detail."  I don't see how "we use" fits with that sentence...?

**Comment by ultrasaurus** [comment]
Note that the +1 could come from a non-18F'er

**Comment by awfrancisco** [comment]
I believe @emileighoutlaw means that you should replace the "--" with a "—" since that is the style 18F uses.

**Comment by ultrasaurus** [comment]
@awfrancisco I made that change!  Also seems like there was a request for addition of "we use" which i didn't understad

**Comment by awfrancisco** [comment]
Oh you are right! I didn't see that before I commented. Whoops!

**Comment by emileighoutlaw** [comment]
My fault! I didn't mean to add "we use" into the text. The edit you made (Andre's comment) was the only thing I meant to draw attention to.

**Comment by ultrasaurus** [comment]
@leahbannon what do you think?

**Comment by leahbannon** [comment]
I actually find this a little more confusing than our original approach, which involved merging after a week if the majority of the people who have weighed in gave it a :+1: Am I misremembering?

**Comment by ultrasaurus** [comment]
@leahbannon that is for code-of-conduct -- waiting a week to merge an addition to a ship checklist feel excessive to me.  Maybe i didn't explain well, but the idea is that anyone can merge someone else's change.  I was just trying to leave room that we might have a contributor from another agency who could :+1: a change from a committer.  Trying to figure out something lightweight for a repo that isn't getting much action.

**Comment by leahbannon** [comment]
We agreed that people should have time to weigh in on substantive changes. I would vote against changing that.

**Comment by DavidEBest** [comment]
Process wise, the compliance toolkit folks (Aidan, Micah, and myself) have been operating in a fashion closer to the "review by one other & leave open for most of a day" than the "leave open for a week & count votes" method.

Should that process be documented here? If so, I think this PR is an adequate representation of that.

**Comment by afeld** [comment]
I say we defer to [the Handbook](https://handbook.18f.gov/github/#process) (which we are actively working on making public) on guidance here, so am closing this. Happy to continue the conversation if folks think we need something specific in this repository.

**Pull request closed without merging**
