### PR TITLE
Update instructions around Privacy Threshold Analysis

### PR DESCRIPTION
**Pull request by andrewmaier**
Add link to official PTA template rather than the proposed one.

### CODE REVIEW

**Comment by afeld** [comment]
Is there an InSite page that says what to do with that doc? The doc itself doesn't seem to say.

**Comment by afeld** [comment]
@rspeidel ^

**Comment by rspeidel** [comment]
Yes, the description is on this insite page:  https://insite.gsa.gov/portal/content/627238
Please ask your colleagues to email it to gsa.privacyact@gsa.gov when complete.  
Thanks,
Richard

**Comment by afeld** [comment]
@rspeidel Great, thanks! You may want to consider including that email on that page or in the doc.

**Pull request merged**
