### PR TITLE
Small FedRAMP Specific Tweaks

### PR DESCRIPTION
**Pull request by thecapacity**

### CODE REVIEW

**Comment by thecapacity** [comment]
@afeld there are some more "substantial" changes I'd also recommend, e.g. _"(FedRAMP requires a further document: a continuous monitoring strategy)"_ is largely inconsequential for 99.9% of 18F projects, because it (the FedRAMP certification and process) only applies to CSP's and I suspect most 18F colleagues will use this guide for applications.

**Comment by hollyallen** [comment]
Thanks @thecapacity !

**Comment by afeld** [comment]
@thecapacity Yeah, the Background page needs work overall...hoping #276 can help guide that. Thanks for the tweaks!

**Comment by thecapacity** [comment]
@afeld totally - let me know if you want to talk through it or anything I somehow had it open in one of my numerous tabs and thought I'd try to do some easy stuff - also @rhoesing is going through documentation now so things like CIS vs. CRM (i.e. two terms for the same concept) should hopefully be reduced!

**Pull request merged**
