### PR TITLE
Update ato.md

### PR DESCRIPTION
**Pull request by adborden**
Fix numbering. I guess step 2 was removed at some point.

### CODE REVIEW

**Comment by afeld** [comment]
It's admittedly a bit confusing, but the skip was intentional as a layer on top of what's at https://atos.open-control.org/steps/. Open to ideas about how to clarify that.

**Comment by adborden** [comment]
Ah, I see. So are you expected to read/follow the Steps from open-control.org or is it background/optional reading?

At minimum, we could at least leave Step 2 in as a placeholder. A sentence explaining why there's no additional effort on top of what's on open-control.org would be helpful too. e.g. _There's nothing to do here. Your controls are selected based on the system's impact level, your infrastructure, the type of ATO, and GSA's existing template._

If the steps from open-control.org are important, we might want to briefly describe the important bits and link to the individual steps to encourage folks to read them.

**Comment by its-a-lisa** [comment]
> It's admittedly a bit confusing, but the skip was intentional. The list is a layer on top of what's at https://atos.open-control.org/steps/, and there isn't anything to add to Step 2. Open to ideas about how to clarify that.

OOO, @afeld -- I don't think I fully understood that either. And I think there (should be) significant TTS specific things that we should be doing at Step 2, so I'll make sure to keep that in mind for when we're developing our organizational documentation.

**Comment by JJediny** [comment]
can circle back on this if needed otherwise, i see no harm in merging

**Pull request merged**
