### PR TITLE
mention who the project is maintained by

### PR DESCRIPTION
**Pull request by afeld**
To address the "who owns this repo?" question in https://github.com/18F/before-you-ship/issues/21.

/cc @ultrasaurus

### CODE REVIEW

**Comment by afeld** [comment]
Bump!

**Comment by DavidEBest** [comment]
Does it matter who owns the repo? The CT team is currently working in the ATO documentation, but I don't follow why we need to claim it.

**Comment by afeld** [comment]
I suppose that's true... @micahsaul, what do you think?

**Comment by micahsaul** [comment]
Sorry for the lack of response, missed the conversation. Personally, having a clear delineation of ownership _somewhere_ makes sense to me. I'd argue that saying the CT team "owns" the ATO section makes sense for now, since that's where the "expertise" currently lives. Having it be just in the readme is fine, but I don't mind it where you put it.

**Comment by afeld** [comment]
Yeah, it's in https://github.com/18F/compliance-toolkit/#things-we-maintain, too (though I probably added that so that's not part of the argument).

**Pull request merged**
