### PR TITLE
Remove DNSSEC doc

### PR DESCRIPTION
**Pull request by konklone**
This removes the DNSSEC doc from this repo. It hasn't been updated in a long time, and has some content and tone issues that warrant revisiting it before we have a public document, especially one with the name "policy" in it.

### CODE REVIEW

**Comment by wslack** [comment]
@konklone is this linked to from anywhere in the repo?

**Comment by wslack** [comment]
Also we should check why circleCI failed.

**Comment by konklone** [comment]
I can't get the [build log ](https://circleci.com/gh/18F/before-you-ship/10) to load, but I'll guess that those are probably related - that by removing the file, I broke links and a linter caught that.

**Comment by brittag** [comment]
@konklone @wslack Yes, it's linked from https://before-you-ship.18f.gov/infrastructure/common-questions/

**Comment by wslack** [comment]
@konklone care to merge https://github.com/18F/before-you-ship/pull/344 ?

**Pull request merged**
