### PR TITLE
remove non-actionable steps in the ATO checklist

### PR DESCRIPTION
**Pull request by afeld**

### CODE REVIEW

**Comment by DavidEBest** [comment]
Are they really non-actionable? 

Selecting controls seems like something that needs to be done relatively early, and with @18F/ato support.
`Implement the controls` is broad, but still requires an the project team to do something, doesn't it?

**Comment by afeld** [comment]
I suppose they _are_ still relevant, but I would like to make the steps a bit more direct, e.g.

> * [ ] Fill out a Masonry template for the current state of your system by following X instructions.
> * [ ] Based on the output from Masonry, make changes in your application so that the security control checks pass for your [ATO level](https://pages.18f.gov/before-you-ship/ato/levels/).

@geramirez Does that sound right? Do you think something like giving teams those instructions is realistic in the near term?

**Comment by DavidEBest** [comment]
Perhaps something like this would work for the short term:

[] Determine, based on a conversation with 18F Infrastructure, the appropriate security controls for the application
[] Document the ways in which your application implements the controls.

Unless, of course, Masonry is ready for prime time. :)

**Comment by geramirez** [comment]
@afeld I think, as long as the person has guidance.

**Comment by afeld** [comment]
@geramirez Could you elaborate?

**Comment by geramirez** [comment]
^^ Maybe we could point people to the cg-compliace now.

**Comment by DavidEBest** [comment]
This is an open question. I need to determine if the transition to CM for 18F apps is being tabled for the time being.

**Pull request closed without merging**
